### ISSUE TITLE
Syntax error with version 1.x.x

### ISSUE THREAD

**Issue by fbozic** [tcollinsworth/axios-cached-dns-resolve#13]
Hi guys,
I'm looking into using you library, but I'm having issues running 1.x.x versions. 

### Source code
```
const axios = require('axios');
import { registerInterceptor } from 'axios-cached-dns-resolve'
import config from '../config';

export default (baseURL: string) => {
  const axiosClient = axios.create({ ...{ baseURL: baseURL }, ...config.axios, ...config.axiosDNS });
  registerInterceptor(axiosClient);

  return axiosClient;
};
```

### How to reproduce
In `package.json` define `"axios-cached-dns-resolve": "^0.5.2"`, run `npm install` and `npm start`. 
- It works fine.

In `package.json` define `"axios-cached-dns-resolve": "^1.2.1"`, run `npm install` and `npm start`. 
- It fails with following stack trace
```
/Users/filipbozic/workspace/infra.sauron.eye/node_modules/axios-cached-dns-resolve/index.js:1
export * from './axios-cached-dns-resolve'
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .js] (/Users/filipbozic/workspace/infra.sauron.eye/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/filipbozic/workspace/infra.sauron.eye/src/httpclient/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
```

**Comment by tcollinsworth** [comment]
The newer versions fix bugs. I'm not maintaining older versions.

**Comment by fbozic** [comment]
But I'm trying to use version `1.2.1` and that one is not working. Older ones are working. I don't see any newer version.
It also fail on runkit: https://npm.runkit.com/axios-cached-dns-resolve

**Comment by tcollinsworth** [comment]
Ah, now I understand. In one of the later versions of the lib I dropped transpiling and used esm. That's why it's complaining for you about export. If you load esm in prior to this library loading, that error will go away. In the latest version of node 14, esm isn't even necessary anymore, but you have to add a module line in package.json and change extensions from .js to .mjs.

**Comment by joewestcott** [comment]
I spent an hour today attempting to import `v1.2.1` in various ways, receiving the same issues as mentioned in the first post.

`v0.5.2` worked perfectly for my needs, preventing `axios` continually re-resolving DNS. Thank you for this library. 😺

**Comment by tcollinsworth** [comment]
For reference:

- What version of node are you using?
- Are you transpiling?
- Are you using esm?

I'll test it out this evening in a new node 14 project.

**Comment by joewestcott** [comment]
Node `v15.3.0`, no transpiling or build system. I've tried ESM `import` and commonJS style `require()` imports. I've tried with and without importing the [esm package](https://www.npmjs.com/package/esm) on line one.

Hope that helps!

**Comment by tcollinsworth** [comment]
I just tried it in a non-esm project and I get the same error. I'll publish a fix in the next few days. I do have a day job.

**Comment by tcollinsworth** [comment]
Just published a new version 2.0.0 that is ES Module/ESM/mjs.

**Comment by joewestcott** [comment]
Hi @tcollinsworth, thanks for this!

In node, using `v2` I'm getting 
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package node_modules/axios-cached-dns-resolve/`

I think `main` in `package.json` needs to be changed to `index.mjs`? Thanks.

**Comment by tcollinsworth** [comment]
My bad. Devils in the details. Updating now.

**Comment by tcollinsworth** [comment]
Done
