### ISSUE TITLE
Can I get similar functionality from https://www.npmjs.com/package/dnscache?

### ISSUE THREAD

**Issue by ssanders1449** [tcollinsworth/axios-cached-dns-resolve#17]
I am already using require('dnscache') in my process. As stated in https://www.npmjs.com/package/dnscache, once that module is enabled, all the subsequent calls to require('dns') are wrapped too.

So, does that mean that I don't need to use axios-cached-dns-resolve? I don't see any calls to require('dns') in axios, so it might be that I still have a problem and need to use axios-cached-dns-resolve instead (or in addition) to 'npm install dnscache'

**Comment by tcollinsworth** [comment]
There is an advantage to my lib. The dnscache increases the latency of requests for resolving dns when it's not in the cache or timed-out. My lib, after the first request keeps the resolution updated in the background as long as it's being used. Therefore requests will not incur the latency of DNS resolution beyond the first. DNS is sometimes very lengthy and that was the purpose of this library; to eliminate the random lengthy latency.

The dnscache git repo is archived and no longer maintained by Yahoo.
