### ISSUE TITLE
Error: Unable to resolve module dns from axios-cached-dns-resolve.js

### ISSUE THREAD

**Issue by WouterFlorijn** [tcollinsworth/axios-cached-dns-resolve#24]
This error shows up when including this package in my project:

```
Error: Unable to resolve module dns from (...)\axios-cached-dns-resolve.js: dns could not be found within the project or in these directories:
  node_modules\axios-cached-dns-resolve\node_modules
  node_modules
```

I'm guessing the required modules are only present server-side, but I'm using Axios client-side. So I was wondering if it's possible to adapt this package to make it more environment-agnostic.

Of course feel free to close this if you think that doesn't make sense, or if that's not the purpose of this package.

**Comment by tcollinsworth** [comment]
This library is designed for node.js.
