### ISSUE TITLE
[Transfer issues from Uptime Kuma] axios-cached-dns-resolve does not work well in some local networks like Tailscale/Wireguard.

### ISSUE THREAD

**Issue by louislam** [tcollinsworth/axios-cached-dns-resolve#27]
### Description

Uptime Kuma was recently added axios-cached-dns-resolve and was released yesterday. Unfortunately, it seems that it is not working well in local environment like Tailscale/Wireguard. After changing back to the normal axios client without [axios-cached-dns-resolve](https://github.com/tcollinsworth/axios-cached-dns-resolve), it is back to normal.

The code changes: https://github.com/louislam/uptime-kuma/pull/1598

#### Related issues

1. It does not resolve local domain names correctly. 
    https://github.com/louislam/uptime-kuma/issues/1821

2. It does not respect /etc/hosts
    https://github.com/louislam/uptime-kuma/issues/1822

### 👟 Reproduction steps

1. Prepare a tailscale/wireguard network
2. Make a request using axios-cached-dns-resolve and using a url with custom domain such as http://my-server:8096

### 👀 Expected behavior

It should be working like a normal axios.

### 😓 Actual Behavior

In my case, it is connection timeout. Someone got `ECONNREFUSED` error.

### Version

axios-cached-dns-resolve: 3.1.0
Node.js 16

**Comment by tcollinsworth** [comment]
Fixed issued with falling back from dns.resolve to dns.lookup. This should fix that issue.
