### ISSUE TITLE
When use in electron/web isomorphic code，it need to introduce on demand

### ISSUE THREAD

**Issue by Wonder233** [tcollinsworth/axios-cached-dns-resolve#39]
hello,
I built an electron and web isomorphic project, and I want to introduced as needed according to the current environment.

like follow:
```
import axios from 'axios'
const axiosIns= axios.create(config);

if (window.process && window.process.platform) {
  const dnsResolve = require('axios-cached-dns-resolve');
  dnsResolve.registerInterceptor(axiosIns);
}

axiosIns.get('xxx');
```

Can this usage be supported?

**Comment by tcollinsworth** [comment]
The library is ESM which use imports and not require. what you want to do is use something like:
```
const dnsResolve = await import('axios-cached-dns-resolve');
```

**Comment by Wonder233** [comment]
Such usage will report an error: 
`const dnsResolve = await import('axios-cached-dns-resolve');`
![image](https://github.com/tcollinsworth/axios-cached-dns-resolve/assets/8199240/0bfb39a4-6429-48e8-b490-951cc9865ae8)

The following are the changes while I forked to your repository. It support both esm and cjs. Can I make a PR?
https://github.com/Wonder233/axios-cached-dns-resolve
