### ISSUE TITLE
Export the library as a CommonJS module

### ISSUE THREAD

**Issue by NikhilVerma** [tcollinsworth/axios-cached-dns-resolve#9]
Thanks for this really useful library! However to use it in most applications it needs to be exported as a CommonJS module. Most bundlers do not process the `node_modules` folder so you get errors like this:

```
export * from './axios-cached-dns-resolve'
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
```

**Comment by NikhilVerma** [comment]
Another solution is to add `"type":"module"` in the package.json as referenced here - https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_package_json_type_field

**Comment by NikhilVerma** [comment]
Just to be clear I am using this in my Next.js app and I had to use additional plugins as NextJS doesn't support `"type":"module"` yet. Related discussion here - https://github.com/vercel/next.js/discussions/13553

**Comment by tcollinsworth** [comment]
I originally implemented it as CommonJS, but since node 10, I'm done with babel transpiling and have converted all my projects to newer style. Just import esm before this module and it will work. My initial index files just import esm and jump to another module with imports. That way when node 14 comes along, I only have one file to touch to remove esm. With node 14.17, I've read that import is finally going to be supported.

**Comment by tcollinsworth** [comment]
I've added type to the package.json.

**Comment by albanm** [comment]
I am using node 16. I get the error "SyntaxError: Cannot use import statement outside a module".

If I set "type": "module" in my package.json I get "require is not defined in ES module scope, you can use import instead".

I don't really care about commonjs vs ecmascript module, but being forced to switch globally for one small dependency doesn't feel right.

Using `const { registerInterceptor } = require('esm')(module)('axios-cached-dns-resolve')` seems to work though. Maybe it would be useful to add something to the doc ?

**Comment by tcollinsworth** [comment]
See README.md [Requirements](https://github.com/tcollinsworth/axios-cached-dns-resolve#requirements)

The esm lib is lacking updates and doesn't currently support optional chaining (elvis), so I've switched to [esm-wallaby](https://www.npmjs.com/package/esm-wallaby) which is a fork of esm that does support optional chaining.

**Comment by albanm** [comment]
I did read the README, I just didn't understand "ECMAScript module (esm), not native esm/.mjs with package.json type: module, requires esm"

I suppose in the first part esm refers to the module system and in the second part to the esm node module that helps loading this type of module.

I was simply saying that something a little bit more explicit, probably with an actual code example, would probably help others.

**Comment by tcollinsworth** [comment]
I don't recommend native esm (type: module, or .mjs extension) because it locks modules from manipulation. Instrumentation with newrelic agent and mocking don't work. Using esm or esm-wallaby supports all the ES6 features but doesn't lock the code.

**Comment by tcollinsworth** [comment]
Thanks for the feedback. I need to update my libraries, so I will take your advice and try to make the docs more clear.
